import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { inspectionPhotographyTemplate as template } from "@/features/photography/inspection-template";
import { assertRequestScope, requestNamespace, requestInputSchema, requestReadiness, requestTemplate, parseAdditionalView, type EvidenceRequest } from "@/features/additional-evidence/request-model";
import { indexedDBRequestRepository as requests } from "@/features/additional-evidence/request-repository";
import { createRequestService, createMockResubmitTransport, requestService } from "@/features/additional-evidence/request-service";
import { readRequestPackage } from "@/features/additional-evidence/request-source";
import { scopedMedia } from "@/features/additional-evidence/scoped-media";
import { fixtureRequest } from "@/features/additional-evidence/request-fixtures";
import { indexedDBSubmissionRepository as submissions } from "@/features/submission/submission-repository";
import { submissionDatabase, isEditLocked, type SubmissionRecord, type InspectionSummary } from "@/features/submission/submission-model";
import { indexedDBPhotoStore, photoKey, readPhoto, photoNamespace } from "@/lib/media/photo-store";
import { indexedDBCaptureDataStore, videoBlobKey } from "@/lib/media/capture-data-store";
import { indexedDBUploadQueue as queue } from "@/features/upload/queue-repository";
import { uploadJobId, type UploadJob } from "@/features/upload/upload-model";
import { additionalDatabaseFixture } from "./additional-idb-fixture";

const originalNamespace = photoNamespace("inspection", template.templateId, template.templateVersion);
const makeRequest = (video = false): EvidenceRequest => ({ id: "request-one", inspectionId: "inspection", version: 1, round: 1, requestedAt: "2026-10-10T07:00:00.000Z", template, originalNamespace, status: "requested", attemptCount: 0, items: video ? [{ id: "video", kind: "video-360", reviewerReason: "یک دور کامل دیده نمی‌شود.", originalEvidenceId: "original-video" }] : [{ id: "front", kind: "photo", requirementId: "front-plate", reviewerReason: "پلاک خوانا نیست.", originalEvidenceId: "original-front" }, { id: "chassis", kind: "photo", requirementId: "chassis-number", reviewerReason: "نزدیک‌تر عکاسی کنید.", originalEvidenceId: "original-chassis" }] });
const original: SubmissionRecord = { inspectionId: "inspection", status: "queued-for-review", idempotencyKey: "initial-key", attemptCount: 1, summary: { namespace: originalNamespace } as InspectionSummary, receipt: { reference: "BDI-8F31K2", submittedAt: "2026-10-08T00:00:00Z", status: "queued-for-review", estimatedReviewMinutes: 120 } };
const scope = (request = makeRequest()) => ({ inspectionId: request.inspectionId, requestId: request.id, version: request.version, kind: "photo" as const, requirementId: "front-plate" });
const photo = () => ({ blob: new Blob(["replacement"], { type: "image/webp" }), capturedAt: "2026-10-10T08:00:00Z" });
async function accepted(request = makeRequest(), index = 0) { const item = request.items[index]; if (item.kind !== "photo") throw new Error("fixture"); const media = scopedMedia(request, item); await media.savePhoto(photo()); await media.confirmPhoto(); }
async function uploaded(request = makeRequest()) {
  const source = await readRequestPackage(request);
  for (const media of source.media) { const job = (await queue.claim("fixture", Date.now()))!; expect(job.id).toBe(uploadJobId(media)); await queue.update(job.id, "fixture", { upload: "uploaded", verification: "processing", owner: undefined, nextCheckAt: Date.now() + 100_000 }); }
}
beforeEach(() => { const db = additionalDatabaseFixture(); db.databases.set(submissionDatabase.name, new Map([[submissionDatabase.records, new Map([[original.inspectionId, original]])]])); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });

describe("scoped domain and derived readiness", () => {
  it("uses configured IDs without adding to twelve photographs/seven sections", () => { const request = makeRequest(); expect(requestInputSchema.safeParse(request).success).toBe(true); expect(requestTemplate(request).sections.flatMap((section) => section.photoRequirements)).toHaveLength(2); expect(template.sections).toHaveLength(7); expect(template.sections.flatMap((section) => section.photoRequirements)).toHaveLength(12); });
  it("rejects unknown, duplicate and video-disabled request targets", () => { const request = makeRequest(); expect(requestInputSchema.safeParse({ ...request, items: [...request.items, request.items[0]] }).success).toBe(false); expect(requestInputSchema.safeParse({ ...request, items: [{ ...request.items[0], requirementId: "CAP-14" }] }).success).toBe(false); expect(requestInputSchema.safeParse({ ...makeRequest(true), template: { ...template, captureRequirements: { video360Required: false } } }).success).toBe(false); });
  it("permits exactly the requested photo while keeping the global submitted lock", () => { expect(assertRequestScope(makeRequest(), original, scope()).id).toBe("front"); expect(isEditLocked(original)).toBe(true); });
  it.each(["rear-plate", "odometer-on", "driver-interior"])("blocks unrequested %s including numeric odometer access", (requirementId) => { expect(() => assertRequestScope(makeRequest(), original, { ...scope(), requirementId })).toThrow("مجاز نیست"); });
  it("rejects wrong inspection, stale version, absent submission and resubmitted requests", () => { const request = makeRequest(); for (const altered of [{ ...scope(), inspectionId: "other" }, { ...scope(), version: 2 }, { ...scope(), requestId: "stale" }]) expect(() => assertRequestScope(request, original, altered)).toThrow(); expect(() => assertRequestScope(request, undefined, scope())).toThrow(); expect(() => assertRequestScope({ ...request, status: "resubmitted" }, original, scope())).toThrow(); });
  it("has no odometer correction capability in its request union", () => { expect(requestInputSchema.safeParse({ ...makeRequest(), items: [{ id: "odo", kind: "odometer", reviewerReason: "edit", originalEvidenceId: "old" }] }).success).toBe(false); });
  it("parses only exact existing capture stages", () => { expect(parseAdditionalView(["photo", "front-plate", "guide"])).toEqual({ kind: "photo", requirementId: "front-plate", stage: "guide" }); expect(parseAdditionalView(["video", "review"])).toEqual({ kind: "video-360", stage: "review" }); expect(parseAdditionalView(["photo", "front-plate", "delete"])).toBeUndefined(); });
  it("requires candidates rather than counting original evidence", () => { expect(requestReadiness(makeRequest(), [], [])).toMatchObject({ total: 2, captured: 0, uploaded: 0, canResubmit: false }); });
});
describe("durable candidates and shared queue", () => {
  it("keeps deterministic fixture IDs stable and unique across submitted inspections", async () => { const request = makeRequest(); await requests.create(request); await accepted(request, 0); await accepted(request, 1); const jobs = (await readRequestPackage(request)).jobs; const first = { ...original, summary: { ...original.summary!, jobs } }; const second = { ...first, inspectionId: "other", summary: { ...first.summary, namespace: photoNamespace("other", template.templateId, template.templateVersion) } }; expect(fixtureRequest(first, "two-photo").id).toBe(fixtureRequest(first, "two-photo").id); expect(fixtureRequest(first, "two-photo").id).not.toBe(fixtureRequest(second, "two-photo").id); expect(fixtureRequest(second, "two-photo").inspectionId).toBe("other"); });
  it("persists requests and reviewer reasons across repository instances", async () => { await requests.create(makeRequest()); expect((await requests.get("request-one"))?.items[0].reviewerReason).toBe("پلاک خوانا نیست."); expect(await requests.list("other")).toEqual([]); });
  it("allows one active round and retains historical rounds", async () => { const request = makeRequest(); await requests.create(request); await expect(requests.create({ ...request, id: "round-two", round: 2 })).rejects.toThrow(); await requests.change(request.id, (current) => ({ ...current, status: "resubmitted" })); await requests.create({ ...request, id: "round-two", round: 2 }); expect((await requests.list("inspection")).map((request) => request.id)).toEqual(["round-two", "request-one"]); });
  it("rejects changing item identity without a new version/round", async () => { const request = makeRequest(); await requests.create(request); await expect(requests.change(request.id, (current) => ({ ...current, items: [] }))).rejects.toThrow("قابل تغییر"); expect((await requests.get(request.id))?.items).toHaveLength(2); });
  it("stores drafts without modifying original evidence or initial submission", async () => { const request = makeRequest(); await requests.create(request); await indexedDBPhotoStore.saveDraft(originalNamespace, "front-plate", photo()); await indexedDBPhotoStore.confirm(originalNamespace, "front-plate"); const before = await readPhoto(photoKey(originalNamespace, "front-plate")); await scopedMedia(request, request.items[0]).savePhoto(photo()); expect((await readPhoto(photoKey(requestNamespace(request), "front-plate")))?.draft?.blob.size).toBeGreaterThan(0); expect(await readPhoto(photoKey(originalNamespace, "front-plate"))).toEqual(before); expect(await submissions.get("inspection")).toEqual(original); });
  it("rechecks authorization on mutation instead of trusting an old UI request", async () => { const request = makeRequest(); await requests.create(request); await requests.change(request.id, (current) => ({ ...current, status: "resubmitted" })); await expect(scopedMedia(request, request.items[0]).savePhoto(photo())).rejects.toThrow("فعال نیست"); });
  it("separates local acceptance from upload and formal resubmission", async () => { const request = makeRequest(); await requests.create(request); await accepted(request); const source = await readRequestPackage(request); expect(source.readiness).toMatchObject({ captured: 1, uploaded: 0, canResubmit: false }); expect(source.media[0]).toMatchObject({ requestId: request.id, requestItemId: "front", replacesEvidenceId: "original-front" }); expect(await submissions.get("inspection")).toEqual(original); });
  it("derives in-progress/ready lifecycle without duplicating item state", async () => { const request = makeRequest(); await requests.create(request); expect((await readRequestPackage(request)).readiness.lifecycle).toBe("requested"); await accepted(request); expect((await readRequestPackage(request)).readiness.lifecycle).toBe("in-progress"); await accepted(request, 1); await uploaded(request); expect((await readRequestPackage(request)).readiness.lifecycle).toBe("ready-to-resubmit"); });
  it("retains accepted candidate through a replacement draft and blocks resubmit until confirmation", async () => { const request = makeRequest(); await requests.create(request); await accepted(request); const before = await readPhoto(photoKey(requestNamespace(request), "front-plate")); await scopedMedia(request, request.items[0]).savePhoto(photo()); const after = await readPhoto(photoKey(requestNamespace(request), "front-plate")); expect(after?.revisionId).toBe(before?.revisionId); expect(after?.blob).toBe(before?.blob); expect((await readRequestPackage(request)).drafts).toEqual(["front"]); await scopedMedia(request, request.items[0]).discardPhotoDraft(); expect((await readPhoto(photoKey(requestNamespace(request), "front-plate")))?.blob).toBe(before?.blob); });
  it("cancels obsolete candidate jobs and rejects stale completion callbacks", async () => { const request = makeRequest(); await requests.create(request); await accepted(request); const job = (await queue.claim("old", Date.now()))!; await accepted(request); expect(await queue.update(job.id, "old", { upload: "uploaded" })).toBe(false); expect((await queue.list()).find((item) => item.id === job.id)).toMatchObject({ current: false, upload: "cancelled" }); });
  it("keeps photo and video in one queue while numeric odometer stays absent", async () => { const request = makeRequest(true); await requests.create(request); const blob = new Blob(["video"], { type: "video/webm" }), media = scopedMedia(request, request.items[0]); await media.saveVideo({ blob, durationSeconds: 28, metadata: { kind: "video-360", localBlobKey: videoBlobKey(requestNamespace(request)), mimeType: blob.type, sizeBytes: blob.size, capturedAt: "now" } }); await media.confirmVideo(); const source = await readRequestPackage(request); expect(source.media).toHaveLength(1); expect(source.media[0].evidenceKind).toBe("video-360"); expect(source.readiness.total).toBe(1); expect((await indexedDBCaptureDataStore.get(requestNamespace(request))).odometer).toBeUndefined(); await expect(media.savePhoto(photo())).rejects.toThrow(); });
  it.each(["queued", "uploading", "failed"] as const)("%s candidate uploads block resubmission", async (upload) => { const request = makeRequest(); await requests.create(request); await accepted(request, 0); await accepted(request, 1); const source = await readRequestPackage(request); const jobs = source.jobs.map((job) => ({ ...job, upload })); expect(requestReadiness(request, source.media, jobs).canResubmit).toBe(false); });
  it.each(["processing", "not-started", "verified"] as const)("binary upload with verification %s counts without claiming reviewer approval", async (verification) => { const request = makeRequest(); await requests.create(request); await accepted(request, 0); await accepted(request, 1); const source = await readRequestPackage(request); const jobs: UploadJob[] = source.jobs.map((job) => ({ ...job, upload: "uploaded", verification })); expect(requestReadiness(request, source.media, jobs).canResubmit).toBe(true); expect(requestReadiness(request, source.media, jobs, ["front"]).canResubmit).toBe(false); });
});
describe("idempotent supplemental submission", () => {
  async function ready() { const request = makeRequest(); await requests.create(request); await accepted(request, 0); await accepted(request, 1); await uploaded(request); return request; }
  it("blocks offline submission without losing durable candidates", async () => { const request = await ready(); await expect(requestService.submit("inspection", request.id, 1, () => false, new AbortController().signal)).rejects.toThrow("اینترنت"); expect((await readRequestPackage(request)).readiness.captured).toBe(2); expect((await requests.get(request.id))?.attemptCount).toBe(0); });
  it("prevents simultaneous duplicate submits and persists a single acknowledgement", async () => { const request = await ready(); const receipt = { reference: "BDI-8F31K2", submittedAt: "2026-10-10T09:00:00Z", evidenceIds: ["one", "two"], status: "queued-for-review" as const }; let finish!: () => void; const transport = { submit: vi.fn(async () => { await new Promise<void>((resolve) => { finish = resolve; }); return receipt; }) }; const service = createRequestService(requests, submissions, transport); const first = service.submit("inspection", request.id, 1, () => true, new AbortController().signal); while (!finish) await Promise.resolve(); const duplicate = await service.submit("inspection", request.id, 1, () => true, new AbortController().signal); expect(duplicate.status).toBe("resubmitting"); finish(); await first; expect(transport.submit).toHaveBeenCalledTimes(1); expect((await requests.get(request.id))?.receipt).toEqual(receipt); });
  it("locks capture while resubmitting at the service boundary", async () => { const request = await ready(); await requests.change(request.id, (current) => ({ ...current, status: "resubmitting", owner: "active", leaseUntil: Date.now() + 30_000 })); await expect(scopedMedia(request, request.items[0]).savePhoto(photo())).rejects.toThrow("فعال نیست"); });
  it("retains stable idempotency on failure/retry and leaves originals unchanged", async () => { const request = await ready(); vi.useFakeTimers(); const service = createRequestService(requests, submissions, createMockResubmitTransport(requests, async () => ({ delayMs: 10, failure: "once" }))); const first = service.submit("inspection", request.id, 1, () => true, new AbortController().signal); const rejection = expect(first).rejects.toThrow("ارسال مدارک"); await vi.runAllTimersAsync(); await rejection; const failed = (await requests.get(request.id))!; const second = service.submit("inspection", request.id, 1, () => true, new AbortController().signal); await vi.runAllTimersAsync(); const result = await second; expect(result.idempotencyKey).toBe(failed.idempotencyKey); expect(result.attemptCount).toBe(2); expect(result.receipt?.reference).toBe(original.receipt?.reference); expect(await submissions.get("inspection")).toEqual(original); });
  it("recovers an uncertain acknowledged response after restart without duplicate submission", async () => { const request = await ready(); vi.useFakeTimers(); const transport = createMockResubmitTransport(requests, async () => ({ delayMs: 10, failure: "uncertain-once" })); const service = createRequestService(requests, submissions, transport); const attempt = service.submit("inspection", request.id, 1, () => true, new AbortController().signal); const rejection = expect(attempt).rejects.toThrow(); await vi.runAllTimersAsync(); await rejection; const freshService = createRequestService(requests, submissions, transport); const recovered = await freshService.recover(request.id); expect(recovered?.status).toBe("resubmitted"); expect(recovered?.attemptCount).toBe(1); await expect(scopedMedia(request, request.items[0]).savePhoto(photo())).rejects.toThrow(); });
  it("releases an abandoned resubmission lease while preserving candidate revisions", async () => { const request = await ready(); await requests.change(request.id, (current) => ({ ...current, status: "resubmitting", owner: "gone", leaseUntil: 0 })); const recovered = await requestService.recover(request.id); expect(recovered?.status).toBe("resubmit-failed"); expect((await readRequestPackage(recovered!)).readiness.captured).toBe(2); });
  it("recovers a crashed media-mutation lease so queue reconciliation can resume", async () => { const request = makeRequest(); await requests.create(request); await requests.change(request.id, (current) => ({ ...current, mutationOwner: "gone", mutationLeaseUntil: 0 })); const recovered = await requestService.recover(request.id); expect(recovered?.mutationOwner).toBeUndefined(); await accepted(recovered!); expect((await readRequestPackage(recovered!)).media).toHaveLength(1); });
  it.each(["capture", "submit"] as const)("stale %s lease recovery cannot release a newly claimed owner", async (kind) => { const request = await ready(); const stale = kind === "capture" ? { mutationOwner: "old", mutationLeaseUntil: 0 } : { status: "resubmitting" as const, owner: "old", leaseUntil: 0 }; await requests.change(request.id, (current) => ({ ...current, ...stale })); const proxy = { ...requests, change: async (id: string, update: (request: EvidenceRequest) => EvidenceRequest) => { await requests.change(id, (current) => kind === "capture" ? { ...current, mutationOwner: "new", mutationLeaseUntil: Date.now() + 20_000 } : { ...current, owner: "new", leaseUntil: Date.now() + 30_000 }); return requests.change(id, update); } }; const service = createRequestService(proxy, submissions, createMockResubmitTransport(proxy)); const recovered = await service.recover(request.id); expect(kind === "capture" ? recovered?.mutationOwner : recovered?.owner).toBe("new"); });
});
